---
database_file: <%= File.join(ENV['HOME'], 'Dropbox/timetrap/timetrap.db') %>
round_in_seconds: 900
append_notes_delimiter: ' '
formatter_search_paths:
- <%= File.join(ENV['HOME'], 'Dropbox/timetrap/formatters') %>
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- <%= File.join(ENV['HOME'], 'Dropbox/timetrap/auto_sheets') %>
default_command: in
auto_checkout: true
require_note: true
